### ISSUE TITLE
Property 'helperService' is used before its initialization

### ISSUE THREAD

**Issue by YucandoIt** [ionictheme/ionic4-start-theme#17]
In charts.page.ts, in the class "ChartPage" , "color: this.helperService.getColorVariable('medium')"  indicate error:  Property 'helperService' is used before its initialization.ts(2729)
charts.page.ts(202, 5): 'helperService' is declared here. I've tried to find a solution with no result..
As a result, the graph is not displayed. Here's the message in the console/

core.mjs:8506 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'getColorVariable')
TypeError: Cannot read properties of undefined (reading 'getColorVariable')
    at new ChartsPage (charts.page.ts:27:37)
    at NodeInjectorFactory.ChartsPage_Factory [as factory] (ɵfac.js:1:1)
    at getNodeInjectable (core.mjs:3485:44)
    at createRootComponent (core.mjs:12391:35)
    at ComponentFactory.create (core.mjs:12272:25)
    at ViewContainerRef.createComponent (core.mjs:21416:47)
    at IonRouterOutlet.activateWith (ionic-angular.js:3488:57)
    at ActivateRoutes.activateRoutes (router.mjs:3048:40)
    at router.mjs:2997:18
    at Array.forEach (<anonymous>)
    at resolvePromise (zone.js:1265:35)
    at resolvePromise (zone.js:1219:21)
    at zone.js:1332:21
    at _ZoneDelegate.invokeTask (zone.js:446:35)
    at core.mjs:23999:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:23999:36)
    at _ZoneDelegate.invokeTask (zone.js:445:64)
    at Object.onInvokeTask (core.mjs:24300:33)
    at _ZoneDelegate.invokeTask (zone.js:445:64)
    at Zone.runTask (zone.js:214:51)

**Comment by firminoweb** [comment]
I will rework it to a new version, and this issue will no longer exist, thank you.
